<template>
  <picture class="smart-pic">
    <source v-if="multi" :srcset="avifSrc" type="image/avif" />
    <source v-if="multi" :srcset="webp" type="image/webp" />
    <img
      :src="src"
      :alt="alt || ''"
      :class="imgClass"
      :style="imgStyle"
      loading="lazy"
      decoding="async"
      @error="$emit('error', $event)"
    />
  </picture>
</template>

<script setup lang="ts">
import { computed, type StyleValue } from 'vue'

// A <picture> wrapper that serves AVIF → WebP → (the given) fallback. The variant
// files are siblings of `src` with the extension swapped (generated by
// scripts/gen-image-variants.mjs). It degrades to a plain <img> when:
//   • src is a data: URI — the offline single-file build inlines ONE format, so there
//     are no .avif/.webp siblings to point at;
//   • src isn't a .png/.jpg/.jpeg (e.g. the cert-placeholder.svg).
// `.smart-pic` is `display: contents` (scoped style below) so the wrapper is
// layout-neutral and existing CSS targeting the inner img class keeps working.
const props = defineProps<{
  src: string
  // Explicit AVIF source (e.g. a base64 data URI). When set it overrides the derived
  // sibling — the offline build inlines the AVIF here while webp/jpg stream from `src`.
  avif?: string
  alt?: string
  imgClass?: string
  imgStyle?: StyleValue
}>()
defineEmits<{ (e: 'error', ev: Event): void }>()

const multi = computed(() => /\.(png|jpe?g)$/i.test(props.src) && !/^data:/i.test(props.src))
const avifSrc = computed(() => props.avif || props.src.replace(/\.(png|jpe?g)$/i, '.avif'))
const webp = computed(() => props.src.replace(/\.(png|jpe?g)$/i, '.webp'))
</script>

<style scoped lang="scss">
/* layout-neutral wrapper so the inner <img> behaves exactly as before
   (existing rules target the img's class; the <picture> box is removed) */
.smart-pic {
  display: contents;
}
</style>
